### ISSUE TITLE
ReferenceError: [BABEL]  Using removed Babel 5 option: base.stage

### ISSUE THREAD

**Issue by eromoe** [happypoulp/redux-tutorial#100]
```
E:\Project\redux-tutorial>babel-node 01_simple-action-creator.js
C:\Users\xxx\AppData\Roaming\npm\node_modules\babel-cli\node_modules\babel-core\lib\transformation\file\logger.js:39
    throw new Constructor(this._buildMessage(msg));
    ^

ReferenceError: [BABEL] E:\Project\redux-tutorial\01_simple-action-creator.js: Using removed Babel 5 option: base.stage
- Check out the corresponding stage-x presets http://babeljs.io/docs/plugins/#presets
    at Logger.error (C:\Users\xxx\AppData\Roaming\npm\node_modules\babel-cli\node_modules\babel-core\lib\transformatio
n\file\logger.js:39:11)
    at OptionManager.mergeOptions (C:\Users\xxx\AppData\Roaming\npm\node_modules\babel-cli\node_modules\babel-core\lib
\transformation\file\options\option-manager.js:265:20)
    at OptionManager.init (C:\Users\xxx\AppData\Roaming\npm\node_modules\babel-cli\node_modules\babel-core\lib\transfo
rmation\file\options\option-manager.js:465:10)
    at File.initOptions (C:\Users\xxx\AppData\Roaming\npm\node_modules\babel-cli\node_modules\babel-core\lib\transform
ation\file\index.js:194:75)
    at new File (C:\Users\xxx\AppData\Roaming\npm\node_modules\babel-cli\node_modules\babel-core\lib\transformation\fi
le\index.js:123:22)
    at Pipeline.transform (C:\Users\xxx\AppData\Roaming\npm\node_modules\babel-cli\node_modules\babel-core\lib\transfo
rmation\pipeline.js:45:16)
    at Object.transformFileSync (C:\Users\xxx\AppData\Roaming\npm\node_modules\babel-cli\node_modules\babel-core\lib\a
pi\node.js:124:10)
    at compile (C:\Users\xxx\AppData\Roaming\npm\node_modules\babel-cli\node_modules\babel-register\lib\node.js:98:20)

    at loader (C:\Users\xxx\AppData\Roaming\npm\node_modules\babel-cli\node_modules\babel-register\lib\node.js:126:14)

    at Object.require.extensions.(anonymous function) [as .js] (C:\Users\xxx\AppData\Roaming\npm\node_modules\babel-cl
i\node_modules\babel-register\lib\node.js:136:7)
```

**Comment by eromoe** [comment]
Sorry, `npm run example 01_simple-action-creator.js` work fine.
But I still don't understand how this command works.
